CREATE DATABASE TIENDA_SI1;
USE TIENDA_SI1;

CREATE TABLE CATEGORIA(
	CATEGORIA VARCHAR(255) PRIMARY KEY NOT NULL,
    CREATEDAT timestamp NOT NULL default NOW()
);

	CREATE TABLE PRODUCTO(
		ID INTEGER auto_increment primary key NOT NULL,
		CODIGO VARCHAR(8) NOT NULL,
		NOMBRE VARCHAR(50) NOT NULL,
		IMAGEN VARCHAR(255) NOT NULL,
		CANTIDAD INT NOT NULL,
		PRECIO FLOAT NOT NULL,
		ESTADO VARCHAR(30),
		CATEGORIA VARCHAR(255),
		CREATEDAT TIMESTAMP NULL default now(),
		UPDATEDAT TIMESTAMP NULL,
		foreign key(CATEGORIA) references 
		CATEGORIA(CATEGORIA) on update CASCADE on delete CASCADE
		);
    
INSERT INTO CATEGORIA (CATEGORIA) VALUES ("LACTEOS");
INSERT INTO CATEGORIA (CATEGORIA) VALUES ("EMBUTIDOS");
INSERT INTO CATEGORIA (CATEGORIA) VALUES ("CARNES");
INSERT INTO CATEGORIA (CATEGORIA) VALUES ("GASEOSAS");
INSERT INTO CATEGORIA (CATEGORIA) VALUES ("BEBIDAS ALCOHOLICAS");
SELECT * FROM CATEGORIA;

INSERT INTO PRODUCTO(CODIGO, NOMBRE, IMAGEN, CANTIDAD, PRECIO, ESTADO, CATEGORIA) VALUES 
("P001", "Cerveza Lager", "cerveza_lager.jpg", 100, 2.50, "Disponible", "Bebidas Alcohólicas"),
("P002", "Vino Tinto", "vino_tinto.jpg", 50, 12.00, "Disponible", "Bebidas Alcohólicas"),
("P003", "Ron Blanco", "ron_blanco.jpg", 75, 15.00, "Disponible", "Bebidas Alcohólicas"),
("P004", "Tequila Blanco", "tequila_blanco.jpg", 30, 25.00, "Disponible", "Bebidas Alcohólicas"),
("P005", "Whisky Escocés", "whisky_escoces.jpg", 60, 40.00, "Disponible", "Bebidas Alcohólicas"),
("P006", "Vodka Premium", "vodka_premium.jpg", 40, 18.50, "Disponible", "Bebidas Alcohólicas"),
("P007", "Champagne Brut", "champagne_brut.jpg", 20, 50.00, "Disponible", "Bebidas Alcohólicas"),
("P008", "Cerveza Artesanal", "cerveza_artesanal.jpg", 120, 3.80, "Disponible", "Bebidas Alcohólicas"),
("P009", "Sidra", "sidra.jpg", 90, 4.00, "Disponible", "Bebidas Alcohólicas"),
("P010", "Cerveza IPA", "cerveza_ipa.jpg", 80, 5.00, "Disponible", "Bebidas Alcohólicas");
SELECT * FROM PRODUCTO;

CREATE TABLE USER (
	USUARIO VARCHAR(50) NOT NULL primary KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) NOT NULL default 'user',
    ACTIVO BOOLEAN NOT NULL default true
);



select * from user;

CREATE TABLE CLIENTE (
	ID INTEGER UNSIGNED auto_increment NOT NULL PRIMARY KEY,
    ID_FACEBOOK VARCHAR(25),
    NOMBRE VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20),
	FOTO TEXT,
    CREATEDAT DATETIME DEFAULT NOW(),
    UPDATEDAT DATETIME
);
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Daniela Gómez", "555-1234");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Carlos Méndez", "555-5678");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Lucía Ramírez", "555-8765");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Juan Pérez", "555-4321");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("María Torres", "555-9876");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Pedro Sánchez", "555-2468");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Laura Herrera", "555-1357");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Andrés Castro", "555-9753");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Ana Morales", "555-4682");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Sofía Jiménez", "555-8596");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Diego Vargas", "555-7412");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Elena Ruiz", "555-3698");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Héctor Rivas", "555-2587");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Valentina López", "555-1479");
INSERT INTO CLIENTE (NOMBRE, TELEFONO) VALUES ("Miguel Navarro", "555-9632");

SELECT * FROM CLIENTE;


CREATE TABLE VENTA(
	NRO INTEGER NOT NULL auto_increment PRIMARY KEY,
    FECHA DATETIME default now(),
    TOTAL DECIMAL(8,2),
    updatedAt DATE,
    ESTADO VARCHAR(20) default 'Autorizado',
    CLIENTE INTEGER UNSIGNED NOT NULL,
    USUARIO VARCHAR(50) NOT NULL,
    foreign key (CLIENTE) references CLIENTE(ID) on update CASCADE on delete CASCADE,
    foreign key (USUARIO) references USER(USUARIO) on update CASCADE on delete CASCADE
);
INSERT INTO VENTA (FECHA, TOTAL, CLIENTE, USUARIO) VALUES ('2025-03-20 14:30:00', 150.75, 1, 'douglas');
INSERT INTO VENTA (FECHA, TOTAL, CLIENTE, USUARIO) VALUES ('2025-03-25 09:15:00', 89.90, 2, 'severitech');
INSERT INTO VENTA (FECHA, TOTAL, CLIENTE, USUARIO) VALUES ('2025-03-22 11:45:00', 250.00, 3, 'severitech1');
INSERT INTO VENTA (FECHA, TOTAL, CLIENTE, USUARIO) VALUES ('2025-03-30 17:20:00', 45.50, 4, 'severitech12');
INSERT INTO VENTA (FECHA, TOTAL, CLIENTE, USUARIO) VALUES ('2025-03-28 13:10:00', 320.99, 5, 'douglas');
INSERT INTO VENTA (FECHA, TOTAL, CLIENTE, USUARIO) VALUES ('2025-04-01 10:05:00', 112.30, 6, 'severitech');
INSERT INTO VENTA (FECHA, TOTAL, CLIENTE, USUARIO) VALUES ('2025-04-03 08:50:00', 78.25, 7, 'severitech1');
INSERT INTO VENTA (FECHA, TOTAL, CLIENTE, USUARIO) VALUES ('2025-03-29 15:40:00', 199.99, 8, 'severitech12');
INSERT INTO VENTA (FECHA, TOTAL, CLIENTE, USUARIO) VALUES ('2025-04-02 12:25:00', 65.00, 9, 'douglas');
INSERT INTO VENTA (FECHA, TOTAL, CLIENTE, USUARIO) VALUES ('2025-04-04 16:35:00', 500.00, 10, 'severitech');

SELECT * FROM VENTA;


CREATE TABLE DETALLE_VENTA(
    VENTA INTEGER UNSIGNED NOT NULL,
    PRODUCTO INTEGER UNSIGNED NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    SUBTOTAL DECIMAL(8,2) NOT NULL,
    PRIMARY KEY (VENTA,PRODUCTO),
    FOREIGN KEY (VENTA) REFERENCES VENTA(NRO) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTO(ID) ON UPDATE CASCADE ON DELETE CASCADE
);
